import { useContext, useEffect, useState } from "react";
import Head from "next/head";
import { getSession, useUser } from "@auth0/nextjs-auth0";

import Navbar from "../components/Navbar";
import Todo from "../components/Todo";
import { table, minifyRecords } from "./api/utils/Airtable";
import { TodosContext } from "../contexts/TodosContext";
import TodoForm from "../components/TodoForm";

export default function Home({ initialTodos }) {
  const { todos, setTodos } = useContext(TodosContext);
  const { user, isLoading } = useUser();

  const [image, setImage] = useState("");

  useEffect(() => {
    setTodos(initialTodos);
  }, []);

  const handleChangeUpload = (e) => {
    setImage(e.target.files[0]);
  };

  const handleUpload = async () => {
    if (!image) {
      return;
    }
    console.log("IMG", image);

    const formData = new FormData();
    formData.append("image", image);

    try {
      const res = await fetch("/api/uploadImage", {
        method: "POST",
        body: formData,
      });

      const data = await res.json();
      console.log("Data Res", data);
    } catch (error) {
      console.log("Error Post", error);
    }
  };

  return (
    <div>
      <Head>
        <title>Todo Airtable</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>
        <div className="m-3">
          <div className="flex items-center">
            <h3>Upload image</h3>
            <button
              className="bg-green-600 text-white py-1 px-4 rounded-lg hover:bg-green-500"
              onClick={handleUpload}>
              Upload
            </button>
          </div>
          <input
            type="file"
            accept=".jpg, .png, .jpeg"
            onChange={handleChangeUpload}
          />
        </div>
        <h1 className="text-2xl text-center mb-4">My Todos</h1>
        {user ? (
          <>
            <TodoForm />
            <ul>
              {todos && todos.map((todo) => <Todo key={todo.id} todo={todo} />)}
            </ul>
          </>
        ) : (
          <p className="text-center mt-4">Please login to save todos!</p>
        )}
      </main>
    </div>
  );
}

export async function getServerSideProps(context) {
  const session = await getSession(context.req, context.res);
  let todos = [];

  if (session?.user) {
    todos = await table
      .select({
        filterByFormula: `userId = '${session.user.sub}'`,
      })
      .firstPage();
  }

  return {
    props: {
      initialTodos: minifyRecords(todos),
      user: session?.user || null,
    },
  };
}
